task_tuple = ("Groceries", "Clean House", "Walk the Dog")
print(task_tuple)
task_tuple = task_tuple + ("Pay Bills",)
print(task_tuple)
temp_list = list(task_tuple)
temp_list.append("Not")
print(temp_list)
temp_list[3] = "Thorn"
print(temp_list)
task_tuple = tuple(temp_list)
print(type(task_tuple))