# Generated by Django 5.1.7 on 2025-04-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description to attract readers. If left empty, a generic description will be displayed.', max_length=300),
        ),
    ]
